title: Wallet Utvecklarportal
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
logo: /assets/images/logo_white.png

# Site settings
lang: sv-SE

# Google Fonts
google_fonts:
  - family: Ubuntu
    weights: [400, 700]

# Exclude files from the final site
exclude:
  - DEVELOPMENT.md
  - README.md
  - Gemfile
  - Gemfile.lock
